config/routes.rb
Rails.application.routes.draw do
  resources :item_categories

  root 'home#index'
  resources :items, only: [:new, :create, :show]

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item_category
end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@item_categories = ItemCategory.all
  end
end

app/controllers/item_categories_controller.rb
class ItemCategoriesController < ApplicationController
  before_action :set_item_category, only: [:show, :edit, :update, :destroy]

  # GET /item_categories
  # GET /item_categories.json
  def index
    @item_categories = ItemCategory.all
  end

  # GET /item_categories/1
  # GET /item_categories/1.json
  def show
  end

  # GET /item_categories/new
  def new
    @item_category = ItemCategory.new
  end

  # GET /item_categories/1/edit
  def edit
  end

  # POST /item_categories
  # POST /item_categories.json
  def create
    @item_category = ItemCategory.new(item_category_params)

    respond_to do |format|
      if @item_category.save
        format.html { redirect_to @item_category, notice: 'Item category was successfully created.' }
        format.json { render :show, status: :created, location: @item_category }
      else
        format.html { render :new }
        format.json { render json: @item_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_categories/1
  # PATCH/PUT /item_categories/1.json
  def update
    respond_to do |format|
      if @item_category.update(item_category_params)
        format.html { redirect_to @item_category, notice: 'Item category was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_category }
      else
        format.html { render :edit }
        format.json { render json: @item_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_categories/1
  # DELETE /item_categories/1.json
  def destroy
    @item_category.destroy
    respond_to do |format|
      format.html { redirect_to item_categories_url, notice: 'Item category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_category
      @item_category = ItemCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_category_params
      params.require(:item_category).permit(:name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    redirect_to @item
  end

  def show
    @item = Item.find(params[:id])
  end

  private

  def item_params
    params.require(:item)
      .permit(:name, :description, :features, :asset_number, :item_category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_categories_helper.rb
module ItemCategoriesHelper
end

app/views/home/index.html.erb
<h1>Welcome to Inventory App</h1>

<h3>Categories:</h3>
<% @item_categories.each do |item_category| %>
	<p><%= item_category.name %></p>
<% end %>

app/views/item_categories/_form.html.erb
<%= form_for(@item_category) do |f| %>
  <% if @item_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_category.errors.count, "error") %> prohibited this item_category from being saved:</h2>

      <ul>
      <% @item_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_categories/edit.html.erb
<h1>Editing item_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_category %> |
<%= link_to 'Back', item_categories_path %>

app/views/item_categories/index.html.erb
<h1>Listing item_categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_categories.each do |item_category| %>
      <tr>
        <td><%= item_category.name %></td>
        <td><%= link_to 'Show', item_category %></td>
        <td><%= link_to 'Edit', edit_item_category_path(item_category) %></td>
        <td><%= link_to 'Destroy', item_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item category', new_item_category_path %>

app/views/item_categories/new.html.erb
<h1>New item_category</h1>

<%= render 'form' %>

<%= link_to 'Back', item_categories_path %>

app/views/item_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item_category.name %>
</p>


<%= link_to 'Create another category', new_item_category_path %>
<%= link_to 'Edit', edit_item_category_path(@item_category) %> |
<%= link_to 'Back', item_categories_path %>

app/views/items/new.html.erb
<%= form_for @item do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :features %>
  <%= f.text_field :features %>
  <%= f.label :asset_number %>
  <%= f.text_field :asset_number %>
  <%= f.label :item_category_id %>
  <%= f.collection_select(:item_category_id, ItemCategory.all, :id, :name) %>
  <%= f.submit %>
<% end %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<p><%= @item.description %></p>
<p><%= @item.features %></p>
<p><%= @item.asset_number %></p>
<p><%= @item.item_category.name %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InventoryApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>